server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mechineTask
    username: root
    password: rinshad3657
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true